FROM php:8.0-apache
EXPOSE 80
#RUN apt-get update && \
 #   apt-get install -y php5-mysql && \
  #  apt-get clean

WORKDIR /var/www/html/

COPY . .

#WORKDIR /frontend

# CMD [ "php", "./backend.php"]

# CMD service apache2 start

#CMD [ "/etc/init.d/apache2", "start"]