variables:
  IMAGE_TAG_FRONTEND: $CI_REGISTRY_IMAGE/sonicast_front:1.0
  IMAGE_TAG_BACKEND: $CI_REGISTRY_IMAGE/sonicast_back:1.0
  IMAGE_NAME_FRONTEND: frontend
  IMAGE_NAME_BACKEND: BackEnd 

stages:
  - build
 # - deploy

default:
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
      # Connect to registry 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

# ---

job_build_frontend:
  #extends: .build_docker_image
  stage: build
  script:
    - cd ${IMAGE_NAME_FRONTEND}
    - docker build -t $IMAGE_TAG_FRONTEND .
    - docker push $IMAGE_TAG_FRONTEND

job_build_backend:
  #extends: .build_docker_image
  stage: build
  script:
    - cd ${IMAGE_NAME_BACKEND}
    - docker build -t $IMAGE_TAG_BACKEND .
    - docker push $IMAGE_TAG_BACKEND
# ---

.job_deploy:
  stage: deploy
  script:
    - echo "This job deploy something."
    - echo "Only when all test jobs are finished."

# ----